version: '3'

services:
  ervice_http:
    labels:
      #uses .env TRAEFIK_CONFIG_SERVICE, TRAEFIK_CONFIG_HOST
      - "traefik.http.routers.${TRAEFIK_CONFIG_SERVICE}.entrypoints=web"
      - "traefik.http.routers.${TRAEFIK_CONFIG_SERVICE}.rule=Host(`${TRAEFIK_CONFIG_HOST}`)"
      - "traefik.http.routers.portainer.priority=0"


